.github/labeler.yml

Adds label to labeler github action

CI:add label

---

boards/m4a-mb/board.c
boards/m4a-mb/include/board.h
boards/m4a-mb/include/gpio_params.h
boards/m4a-mb/include/periph_conf.h
boards/stm32f469i-disco/board.c
boards/stm32f469i-disco/include/board.h
boards/stm32f469i-disco/include/gpio_params.h
boards/stm32f469i-disco/include/periph_conf.h
firmware/main.c
tests/board_stm32f469i-disco/main.c
tests/test_driver_epd-bw-spi/epd_bw_spi_params.h
tests/test_driver_epd-bw-spi/main.c

Update header info for  licenses compliance

doc: update license header

---

README.md
boards/m4a-mb/board.c
boards/m4a-mb/include/board.h
boards/m4a-mb/include/gpio_params.h
boards/m4a-mb/include/periph_conf.h
boards/stm32f469i-disco/board.c
boards/stm32f469i-disco/include/board.h
boards/stm32f469i-disco/include/gpio_params.h
boards/stm32f469i-disco/include/periph_conf.h
firmware/main.c
tests/board_stm32f469i-disco/main.c
tests/test_driver_epd-bw-spi/epd_bw_spi_params.h
tests/test_driver_epd-bw-spi/main.c

Update README, adding some secctions and updating others

documentaion: Update README

---

CONTRIBUTING.md

This is a PR to insert some content to CONTRIBUTING.md, the same was applied to m4ag-firmware. I changed the reference links, directory referenced in CLI getting started.  I added a link to the issues list and i fixed the third item from the Contributing Code Section

docs: Add Contributing Guidelines

---

CONTRIBUTORS

This is a PR to add the Collaborators file, where are all the collaborators who work in this repository.

docs:  Add the Contributors file

---

.github/ISSUE_TEMPLATE/bug_report.md

Update `.github/ISSUE_TEMPLATE/bug_report.md` for better understanding
Try to open a new issue and select bug or read ``.github/ISSUE_TEMPLATE/bug_report.md` `
This fix #35

doc: Update issue template

---

README.md

This is a PR to update the README, document
fix #38

docs: Modifying Readme file

---

Makefile

Fix a bug in the build process
execute in the root folder:
```sh
make
```
None

build: fix compilation error

---

README.md
boards/m4a-mb/board.c
boards/m4a-mb/doc.txt
doc/media/readme.txt
firmware/Makefile
tests/driver_epd-bw-spi/Makefile
tests/driver_epd-bw-spi/README.md
tests/driver_epd-bw-spi/epd_bw_spi_params.h
tests/driver_u8g2/Makefile
tests/periph_uart/main.c

This is a Pull Request dedicated to resolve bugs founded in the static-test. We work with the corrections to the code and documentation 
in the directory m4a-firmware execute:
```sh
make static-test
```
testing one by one static-test
```sh
cd dist/tools
```
When you're in the dist/tool directory take a list of documents inside the folder.
```sh
ls
cd whitespacecheck // This is a example static-test folder  
./check.sh
```
Related to  #34

ci: static-tests fix errors and warnings - round 2

---

dist/tools/utils/depends.sh

PR dedicated to add the script bash/UNIX to auto download all required dependencies for static-test 
enter your repository m4ag-firmware and then execute
```sh
./depends.sh
```
fix #47

sh: Adding script dependencies

---

README.md

This  small change adds a badge status for docs  deployment action.
In the README.md should appear a new badge status, 
None

doc: add badge for docs deployment

---

doc/doxygen/src/html/footer.html

fixes bad image source:
go to: https://mesh4all.github.io/m4a-firmware/ and look at the footer section
None

doc: fix doxygen image src

---

doc/doxygen/m4a.doxyfile
doc/source/mainpage.md

Add a folder as source for default pages for some sections and templates
Check out  source files, it should be placed into doc/source folder

documents sources for doxygen

---

.gitmodules

Update submodules from git to https
Init and updating submodules should work as spected:
```sh
git submodule update --init --recursive
``` 
None

update submodule 

---

CODING_CONVENTIONS.md

In this PR will be provide some examples in the file CODING_CONVENTIONS, this will give to the user an important structure about how to should to write the doxygen documentation headers

doc: Coding_convention example changed

---

CONTRIBUTORS

was updated CONTRIBUTORS.md
this PR fixes the issue #55

doc:update CONTRIBUTORS.md

---

CODING_CONVENTIONS.md

Take the organization identifier to the license headers, to build the documentation. Apply a little changes in Coding_Convention to make all changes in every example, test, drivers and includes folders. Is Strictly required to maintain an order and a structure of documentation in every file .c .cpp .h .hpp

doc: Updating Coding_Conventions_header_file_license

---

.drone.yml

First step, adding external CI integration 
really this change is not fully functional, so there is nothing to expect
#72

ci: continuous integration, step 1

---

.drone.yml

Add triggers  for the CI system
Nothing special,  this PR should show us **Luke-Skywalker" in action

ci: update drone.yml

---

firmware/Makefile
firmware/peripherals/moisture_sensor/Makefile
firmware/peripherals/moisture_sensor/Makefile.dep
firmware/peripherals/moisture_sensor/Makefile.include
firmware/peripherals/moisture_sensor/include/moisture_sensor.h
firmware/peripherals/moisture_sensor/moisture_sensor.c

Contribution description
this is the implementation of the moisture sensor
Issues/PRs references
this PR fixes the issue #76

feature: add moisture sensor

---

.drone.yml
boards/m4a-wrover/Kconfig
boards/m4a-wrover/Makefile
boards/m4a-wrover/Makefile.dep
boards/m4a-wrover/Makefile.features
boards/m4a-wrover/Makefile.include
boards/m4a-wrover/doc.txt
boards/m4a-wrover/include/board.h
boards/m4a-wrover/include/gpio_params.h
boards/m4a-wrover/include/periph_conf.h
firmware/main.c

this PR is an implementation of the board m4a-wrover-kit with all definitions that we need for the peripherals
this PR  fixes #81

boards: add m4a-wrover

---

firmware/libs/serialization/Makefile
firmware/libs/serialization/Makefile.dep
firmware/libs/serialization/Makefile.include
firmware/libs/serialization/include/serialization.h
firmware/libs/serialization/serialization.c

Was added  tinycbor  and added the serialization functions also was add the libs folder.
this PR  fixes #82

libs: added  cbor serialization

---

examples/TPM_UART_APP/main.c
examples/esp32-wrover-app/external_modules/cJSON/cjson.c
examples/esp32-wrover-app/external_modules/cJSON/include/cjson.h
examples/esp32-wrover-app/main.c
examples/esp32-wrover-app/udpf.c
examples/esp32-wrover-app/udpf.h
examples/external_led/main.c

This Pr will be make changes over all static warnings in example folders, This apply all proposals to coccinelle  and whitespacechecks
fix #99

Fixed old static test warnings

---

doc/doxygen/m4a.doxyfile
examples/doc.txt
examples/esp32-wroom-32/slipdev/README.md
examples/esp32-wroom-32/slipdev/doc.txt
examples/esp32-wroom-32/slipdev/main.c
examples/esp32-wroom-32/slipdev/slipdev_params.h
examples/esp32-wroom-32/test_ds18b20/Makefile
examples/esp32-wroom-32/test_ds18b20/README.md
examples/esp32-wroom-32/test_ds18b20/doc.txt
examples/esp32-wroom-32/test_ds18b20/ds18b20.h
examples/esp32-wroom-32/test_ds18b20/main.c
examples/esp32-wrover-app/Makefile
examples/esp32-wrover-app/doc.txt
examples/esp32-wrover-app/external_modules/cJSON/cjson.c
examples/esp32-wrover-app/external_modules/cJSON/include/cjson.h
examples/esp32-wrover-app/main.c
examples/esp32-wrover-app/udpf.h
examples/external_led/Makefile
examples/external_led/README.md
examples/external_led/doc.txt
examples/external_led/main.c
examples/moisture_sensor_hw390/Makefile
examples/moisture_sensor_hw390/doc.txt
examples/moisture_sensor_hw390/main.c
examples/moisture_sensor_hw390/readme.md
examples/tmp_uart/Makefile
examples/tmp_uart/README.md
examples/tmp_uart/doc.txt
examples/tmp_uart/main.c

PR dedicated to replace some target boards from examples and change his documentation, this will be complement these sources

Resolve some targets of examples and his doc

---

.drone.yml

Luke  does builds or tests in a linear fashion right now,  but this is inefficient,  it could be a matrix build  and reduce PR's check times.
This PR update the structure of the .yaml file , adding builds or test  in a matrix flavour .
Wait for the green check of Luke , click on details, in the ci site , on the upper side click on graph view
None

CI: matrix builds

---

CODING_CONVENTIONS.md

header license update to the late version
look at CODING_CONVENTIONS.md  on the root folder.
None

doc:update coding_conventions

---

wifi-subsys/components/doc.txt
wifi-subsys/components/network/src/wifi.h
wifi-subsys/main/default_params.h

Fix an old error related to doxygen groups 
On the root folder execute:
```sh
make static-test
```
Expected green on doccheck script
None

ci: fix doxygen groups

---

.clang-format

This PR add a file with the needed formatting rules for `clang-format` 
The file is on the root folder, `.clang-format`, you can try to format some code or look at the rules opening the file any text editor
None

tools: add clang format options

---

wifi-subsys/components/network/src/wifi.c
wifi-subsys/components/protocols/src/icmp_ping.c
wifi-subsys/main/CMakeLists.txt
wifi-subsys/main/default_params.h
wifi-subsys/main/main.c

in this PR was added the implementation and initialization of all components created for wifi subsys.
this pr still in progress only missing add sntp settings i have some problems with the internet and i can not continue. please see the code and share with me your opinions.

wifi-subsys: add main of wifi subsys

---

wifi-subsys/components/protocols/src/protocol_sntp.c
wifi-subsys/components/protocols/src/protocol_sntp.h
wifi-subsys/components/protocols/test/test_sntp.c
wifi-subsys/main/default_params.h

This PR is dedicated to integrate some resources to convert the sntp protocol to efficient sync time with an stnp server. Itś create a task that will be executed during the synchronization with the sntp server, this task, does some calls to anoters functions that could be passed as params. so the only necessary function to call the sntp process is sntp_start(), this receives as param a function of type void and that has a single param of type time_t. 
Fixes #143

Wifi-subsys: SNTP update

---

wifi-subsys/components/protocols/src/icmp_ping.c
wifi-subsys/components/protocols/src/icmp_ping.h
wifi-subsys/components/protocols/test/test_icmp.c
wifi-subsys/main/default_params.h

Add milliseconds between each ping procedure
Add a “ping” session contains count procedures
Delete vTaskDelay
look at wifi-subsys/components/protocols/icmp_ping.c
- esp_ping_confing_t struct
look at wifi-subsys/main/default_params.h
- #define PING_INT 5000                                /* Milliseconds between each ping procedure*/
#define PING_RET 3                                /* A “ping” session contains count procedures*/
#define PING_TIMEOUT 600000              /* Repeat task when timeout finishes*/
Fixes #144

wifi-subsys: icmp_ping

---

wifi-subsys/main/default_params.h
wifi-subsys/main/main.c

this PR completes the flow of main,  were added all variables in the nvs   necessary for the startup of each module and the initial startup time was added.
to compile:
`idf.py build `
to flash: 
`idf.py  -p /dev/tty.usbserial-142301 flash`
this PR is related #142

wifi-subsys: main component

---

wifi-subsys/main/main.c

fixed a small typing error in main.

wifi-subsys: fix little error in main

---

wifi-subsys/components/network/src/wifi.c
wifi-subsys/components/network/src/wifi.h
wifi-subsys/components/uart/src/at_handler.c
wifi-subsys/components/uart/src/at_handler.h
wifi-subsys/components/uart/src/subsys_uart.c
wifi-subsys/components/uart/src/subsys_uart.h

in this PR was separated AT module and uart also the AT handler was modified for work with different actions. the handler was divided in sections handler actions and write handler, also it was prepared for read actions y responses of the all functions executed.
Run the related tests running the following in the test folder:

wifi-subsys: update uart structure

---

wifi-subsys/main/default_params.h
wifi-subsys/main/main.c

small modifications were added to main.c so that it does not always take the default values of default_params.h a variable was also added in default_params.h to force the saving of the default parameters in the nvs
to compile:
`idf.py build`
to flash and enabled console:
`idf.py -p /dev/tty.usbserial-0001 flash  monitor`

wifi-subsys: main update

---

wifi-subsys/components/network/src/wifi.c
wifi-subsys/components/network/src/wifi.h
wifi-subsys/components/uart/src/at_handler.c
wifi-subsys/components/uart/src/subsys_uart.c

Some bugs were found in Wi-Fi at the time of the tests, these were:
1) error when trying to change wifi data once it is turned off
2) run wifi_stop in a row
3) switch from ap to ap_sta mode
to compile:
`idf.py build`
to flash and enabled console:
`idf.py -p /dev/tty.usbserial-0001 flash  monitor`

wifi-subsys: fix litle bugs

---

.clang-format

change SortIncludes in clang format
*SortIncludes: false
Look at clang format line 110

clang-format

---

CONTRIBUTORS
README.md

Changes in documentation. Specifically in Readme. I deleted an installation link, update the copyright and added a link to Telegram
look at README.md
none

readme: changes in documentation

---

tests/Makefile.tests_common
tests/serialization/Makefile
tests/serialization/app.config.test
tests/serialization/main.c
tests/serialization/tests/01-run.py

Added unit tests to the serialization module.
cd test/serialization
make BOARD="your_board" flash term

test: added test to serilization module

---

tests/uniqueid/Kconfig
tests/uniqueid/Makefile
tests/uniqueid/app.config.test
tests/uniqueid/main.c
tests/uniqueid/tests/01-run.py

Added test to unique id component.
cd test/uniqueid
make BOARD="your_board" flash term

test: test to unique id module

---

firmware/sys/uniqueid/doc.txt

The doc.txt was used to explain the operation of the uniqueid module
look at firmware/sys/doc.txt
fixes #186

sys: change doc.txt uniqueid

---

boards/m4a-24g/include/board.h
boards/m4a-mb/include/board.h
boards/m4a-wroom/include/board.h
boards/m4a-wrover/include/board.h

Delete uniqueid.h on m4a-24g.h, m4a-mb.h, m4a-wroon, m4a-wrover at boars.
Look at boards
Fixes #201

boards: delete uniqueid.h

---

firmware/sys/at_client/doc.txt
firmware/sys/at_client/include/at_client.h

Documentation for the at_client module was written
Look at firmware/sys/at_client/doc.txt

sys/docs: at_client documentation

---

tests/serialization/doc.txt
tests/storage/doc.txt

he doc.txt was added to the serialization test module where it is explained how to execute it

doc: added doc.txt to storage test

---

wifi-subsys/components/protocols/src/httpsclient.c
wifi-subsys/components/protocols/src/httpsclient.h
wifi-subsys/components/protocols/test/test_https.c

This contributions add to wi-fi-subsystem a threading test of https get and post method. The principal goal is remove all delays existing to generate a request for an server. The resources existing integrates some delays to get an response of server, but this, is a significant time, could be stop the firmware, during its proccess.
If you want to start testing only upload the wifi-subsytem/test resource
```sh
```
Fixes #218

Wifi-subsys: Upgrade_test_https_GET_and_POST

---

boards/m4a-24g/include/eui_provider_params.h

This is to include eui_provider.h header files, this will let work with eui64 to the m4a-24g board

boards: eui_provider_integration to m4a-24g

---

boards/m4a-24g/Makefile.dep

This Solve a little dependency of module eui64

boards: eui64_provider fixed dependencies

---

boards/doc.txt
boards/m4a-24g/Kconfig
boards/m4a-24g/Makefile.features
boards/m4a-24g/dist/openocd.cfg
boards/m4a-mb/Makefile.features

It's a  bootloader that adds USB device firmware upgrade (DFU) support
It's a  bootloader that adds USB device firmware upgrade (DFU) support:
- Go to RIOT/bootloaders/riotboot_dfu folder and use the command
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make term flash
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This sets USB port with VID =1209, PID = 7D02.
Below are the steps to update the firmware:
- Compile with the following command
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
FEATURES_REQUIRED+=riotboot USEMODULE+=usbus_dfu make BOARD=m4a-24g
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
with this you get a .bin file located at <project_folder>/bin
- Switch to USB …

Boards: riotboot dfu support

---

doc/doxygen/m4a.doxyfile

This Pr brings the solution to exclude all markdown files in each example directory. only has a change in the m4a_doxyfile to set this rule. 
To see the documentation in te current state, connect with this branch ands them run 
```sh
make docs
```
The current output should to see this:

doc: doxyfile_ control to README from examples!

---

firmware/network/Makefile
firmware/network/border_router/Makefile
firmware/network/border_router/Makefile.dep
firmware/network/border_router/Makefile.include
firmware/network/border_router/border_router.c
firmware/network/border_router/doc.txt
firmware/network/border_router/include/border_router.h
tests/border_router/Makefile
tests/border_router/app.config.test
tests/border_router/doc.txt
tests/border_router/main.c
tests/border_router/tests/01-run.py

Border router using the USB CDC ECM, this module create config ipv6 host.
look at firmware/network/border_router
Testing with 
```
ipv6_addr_t address = {
.u8 = {0},
};
ipv6_addr_from_str(&address,"2001:db8:1::2");
ipv6_addr_print(&address);
border_router_ipv6_config(_UNICAST,&address);
```
none

Network: border router ipv6 config host

---

wifi-subsys/components/network/CMakeLists.txt
wifi-subsys/components/protocols/CMakeLists.txt
wifi-subsys/components/protocols/src/httpsclient.h
wifi-subsys/components/uart/CMakeLists.txt
wifi-subsys/components/uart/src/subsys_uart.c
wifi-subsys/components/uart/src/subsys_uart.h

modifications were made to be able to wifi-subsys so that when sensor data arrive they are sent to the remote server changes were also added to the https client to send cbor values

wifi-subsys: added functionality to send messages to server from uart

---

firmware/sys/serialization/include/serialization.h
firmware/sys/serialization/serialization.c

The decoding and encoding functions of the serialization module were modified. The structure was also modified so that it contains the id of the node that is sending the data.
cd test/serialization
make flash test

firmware: added node id to enconde and decode function

---

examples/system_example/Kconfig
examples/system_example/Makefile
examples/system_example/main.c
examples/system_example/readme.md

was built a little example where is added the initial workflow of `Mesh4All` app this example uses all the modules developed previously
there are two modes Dodag and dag every mode has a workflow the working example is:
1)  Dogag(master node) this node executes a server UDP and receives all data sent by node dag, one-time UDP server gets data, this data is sent through uart to the esp32 the esp32  will receive the data and it will send the data to the server.
1) DAG (slave node) this node keeps connected to the sensors there is defined a time where get the sensor's information and serialize the information with CBOR protocol and send it to the Dodag node through a UDP client
To test this example you must have at least two boards samr21 and one board esp32(Wrover-kit or Wroom) and …

Mesh4all workflow example

---

examples/mesh4all_rpl/Kconfig
examples/mesh4all_rpl/Makefile
examples/mesh4all_rpl/main.c
firmware/network/radio/radio.c
firmware/network/rpl_protocol/Makefile.dep

Tests were made with several nodes from iot-lab and I could notice that the connection with rpl was not working correctly, the changes were:
1) added gnrc_ipv6_router_default
2) a condition was added so that when the nodes are dodag the global address is not created
3) an example was added to better use the rpl functions from iot-lab
make -C  examples/mesh4all-rpl

firmware: rpl fixed routing

---

examples/system_example/main.c

the example was updated due to the recent changes in the modules de Rpl 
Make -C  examples/system_example flash term

examples: update test with the last changes in rpl module

---

dist/tools/m4a-generator/m4agen/application.py
dist/tools/m4a-generator/m4agen/board.py
dist/tools/m4a-generator/m4agen/example.py
dist/tools/m4a-generator/m4agen/module.py
dist/tools/m4a-generator/m4agen/templates/application/main.c.j2
dist/tools/m4a-generator/m4agen/templates/board/board.h.j2
dist/tools/m4a-generator/m4agen/templates/board/doc.txt.j2
dist/tools/m4a-generator/m4agen/templates/board/periph_conf.h.j2
dist/tools/m4a-generator/m4agen/templates/module/Makefile.dep.j2
dist/tools/m4a-generator/m4agen/templates/module/Makefile.include.j2
dist/tools/m4a-generator/m4agen/templates/module/module.c.j2
dist/tools/m4a-generator/m4agen/test.py

The m4a-generator isn't building all files required. the new format has the following features:
- Solved Makefiles.dep and Makefile.include
- In example template will be placed the sign of Mesh4all, when it's referred an m4agen application.
You will need to uninstall de previous installed m4agen
```sh
sudo pip uninstall m4agen
```
You could repeat the steps of #246 or only run in the base directory m4a-firmware/ the generator commands:
```Makefile
make generate-module
```
You will has the following message, if you want to install m4agen press only the key "y". *note*: when you accept this process you need to enter your sudo password.
```sh
/bin/sh: 5: 'm4agen' command is not available please consider installing it from https://pypi.python.org/pypi/m4agen: not found
m4a-template-generator …
```

dist/tools/m4a-generator: Fixed some makefile includes and templates

---

examples/mesh4all_rpl_dag/main.c
firmware/main.c
firmware/sys/at_client/at_client.c
firmware/sys/storage/storage.c

RIOT was updated to the latest version

riot update

---

wifi-subsys/components/network/test/test_wifi.c
wifi-subsys/components/protocols/src/httpsclient.c
wifi-subsys/components/protocols/src/icmp_ping.c
wifi-subsys/components/protocols/test/test_https.c
wifi-subsys/components/protocols/test/test_icmp.c
wifi-subsys/components/storage/test/test_nvs.c
wifi-subsys/components/tools/test/test_serialization.c
wifi-subsys/components/uart/src/at_handler.c
wifi-subsys/components/uart/src/subsys_uart.c
wifi-subsys/components/uart/test/uart_test.c
wifi-subsys/main/main.c

This Pr is dedicated to fix all static warnings presented in the github about the wifi-subsys

wifi-subsys: fixed old static warnings presents

---

examples/ds18b20/README.md
examples/ds18b20/main.c
firmware/peripherals/ds18_sensor/ds18_sensor.c

This is an ds18b20 correcction to obtains the correct values under the 0 grades., was fixed the error presenting two values negatives in the integer number and the decimal number. was removed unused variables from the ds18b20 peripherals.
```
make -C examples/ds18b20 flash term
```

example: updated ds18b20 sensors, fixed reading data under 0 grades

---

firmware/sys/at_client/doc.txt
firmware/sys/doc.txt
firmware/sys/serialization/doc.txt
firmware/sys/storage/doc.txt
firmware/sys/uniqueid/doc.txt

Make documentation corrections in the group Sys and the following modules:
-at_client
-Serialization
-Storage
-uniqueid
In to the console write:
```
make docs
```
and go to  doc/doxygen/html/index.html
fixes : #281, #282

Sys: documents corrections

---

boards/m4a-24g/include/board.h
boards/m4a-mb/include/board.h
firmware/sys/uniqueid/include/uniqueid.h

Remove cpuid_get(id) of board.h and move it into uniqueid.h library,
Look at firmware/sys/uniqueid/include/uniqueid.h
fixes #292

Sys: move cpuid to uniqueid

---

firmware/network/radio/Makefile.dep
firmware/sys/uniqueid/Makefile.dep
firmware/sys/uniqueid/uniqueid.c
tests/uniqueid/main.c
tests/uniqueid/random_gen.c
tests/uniqueid/unique_random.h

This Pr add support to uniqueid in native boards, and use the `periph_hwrng` to provide a random `uint32_t` value. So the use of netopt `NETOPT_RANDOM`will give it to the boards with radio integrated.  The radio module will be loaded only when the board has an radio interface, if this interface doesn't exist, will use the `periph_hwrng` to provide an random value of uniqueid. Also removes the uniqueid dependency from the radio module, this itself doesn't need pre-load to use it.
in the section uniqueid you have to configurate to the random, for see the random number generator running.
```
make menuconfig -C tests/uniqueid flash term
```
Fixes #293

sys/uniqueid: Fixed rendundancy code and dependencies to multi support

---

firmware/network/Kconfig
firmware/network/net_tools/Kconfig
firmware/network/net_tools/net_tools.c
tests/border_router/Kconfig

Made kconfig to net tools module with the kconfig sets the configuration to prefix displacement.
Run in terminal ``` make menuconfig```, look for the option net tools  and choose a number to prefix displacement.

Network: made kconfig to net tools

---

examples/system_example/main.c
firmware/network/udp_client/Kconfig
firmware/network/udp_client/include/udp_client.h
firmware/network/udp_server/Kconfig
firmware/network/udp_server/include/udp_server.h
firmware/network/udp_server/udp_server.c
tests/udp_client/Kconfig
tests/udp_client/main.c
tests/udp_server/Kconfig
tests/udp_server/main.c

Made kconfig to udp_server and udp_client modules with the kconfig sets the configuration to port
Run in terminal make menuconfig, look for the option udp_client or udp_server and choose of port

Network: Made kconfig to udp_server and udp_client

---

examples/mesh4all_rpl_dodag/main.c
examples/slipdev/main.c
examples/system_example/main.c
firmware/network/radio/Makefile.dep
firmware/sys/uniqueid/Makefile.dep
firmware/sys/uniqueid/uniqueid.c
tests/uniqueid/main.c
tests/uniqueid/random_gen.c
tests/uniqueid/unique_random.h

Make some changes to fix the section example because the  ```shell_commands.h``` library was removed
Look at ```examples``` and choose between of modules an run with ``` make flash term```
fixes #301

Examples: Fixed module

---

boards/vs203/Kconfig
boards/vs203/Makefile
boards/vs203/Makefile.dep
boards/vs203/Makefile.features
boards/vs203/Makefile.include
boards/vs203/board.c
boards/vs203/doc.txt
boards/vs203/include/board.h
boards/vs203/include/gpio_params.h
boards/vs203/include/periph_conf.h

Basic implementation of Vision's `VS203` USB, dongle (cc2538+cc2592).
Compile and flash the firmware, some example or a test.
None

board: initial implementation of `VS201` board, `CC2538 + CC2592`

---

firmware/network/net_tools/include/net_tools.h
firmware/network/net_tools/net_tools.c
firmware/sys/uniqueid/include/uniqueid.h
firmware/sys/uniqueid/uniqueid.c
tests/net_net_tools/Makefile
tests/net_net_tools/main.c
tests/net_net_tools/tests/01-run.py
tests/system_uniqueid/main.c

In this PR are integrated new testing features to net_tools functions. Was added a function to remove an ipv6 global address from an interface. and will brings support to native board.
Go to the new testr net_tools:
```
make -C tests/net_net_tools/  flash term
```
Run the same test in native board.
```
make -C tests/net_net_tools/ all BOARD=native term
```

Test/net tools: Integration to net_tools test

---

firmware/default_params.h
firmware/sys/shell_extended/se_storage.c
firmware/sys/storage/include/storage.h
firmware/sys/storage/include/storage_register.h
firmware/sys/storage/storage.c
firmware/sys/storage/storage_internal.c
firmware/sys/storage/storage_register.c
tests/system_storage/main.c

This will update the shell extended commands, it adds support for manage storage commands, saviing and loading settings for all netwrok modules, giving some features to Border Router implementations and RPL. 
```
make -C example/shell_extended flash term
```

firmware/sys/shell_extended: Added support of network modules for Stg_cmd 

---

README.md

This Pr fixes a badge bugs in README.md file, was replaced badge syntax from HTML to Markdown... The URL of badge build-docs was fixed with the reference from the github actions.
Fixes #371

doc: Replace html badges with markdown Syntax

---

README.md

This PR fixed links of Documentation and redirect an user to the compiled Repository's Documentation.

doc: fixed link badges
