- firmware/Makefile
- firmware/main.c
Module **gnrc_netdev_default** is deprecated, the new one to be used is **netdev_default**
> delete deprecated modules <gnrc_netdev_default>

- .github/workflows/compilation_check.yml
Github actions raises error when building process is trying to download the toolchain from the  arm site.
This change try to install the toolchain from Ubuntu repos.
> CI:fix_certificate_warning

- CODING_CONVENTIONS.md
A file named `CODING_CONVENTIONS.md` in the root folder with some requirements avoiding bad practices
None in special, only read `CODING_CONVENTIONS.md` and let me your opinion
This PR fix #28
> docs: Add CODING_CONVENTIONS.md file

- dist/tools/codespell/check.sh
This PR is dedicated to resolve the issues from codespell static-test. We want to ignore the doxygen docs to resolve this
General static-tests in the first directory m4a-firmware
```sh
make static-test
```
Using the local static test
```sh
cd dist/tools/codespell
./check.sh
```
> ci: Fix Codespell Doxygen

- .drone.yml
- boards/m4a-wroom/Kconfig
- boards/m4a-wroom/Makefile
- boards/m4a-wroom/Makefile.dep
- boards/m4a-wroom/Makefile.features
- boards/m4a-wroom/Makefile.include
- boards/m4a-wroom/doc.txt
- boards/m4a-wroom/include/board.h
- boards/m4a-wroom/include/gpio_params.h
- boards/m4a-wroom/include/periph_conf.h
Pr to bring support of the esp32 board required in the issue #84, this follow the client model, taking the sensors pin defaults and the new UART2 to maintain the Slipdev protocol 
fix #84
> boards: adding support to m4a-wroom

- wifi-subsys/components/uart/CMakeLists.txt
- wifi-subsys/components/uart/src/subsys_uart.c
- wifi-subsys/components/uart/src/subsys_uart.h
- wifi-subsys/components/uart/test/CMakeLists.txt
- wifi-subsys/components/uart/test/uart_test.c
simple async uart implementation for use with AT commands and could receive sensor datos for send to the cloud.
This is an initial implementation for the communication between the boards throw uart protocol.
`cd test && idf.py build -D "TEST_COMPONENTS=uart" flash monitor`
```sh
Here's the test menu, pick your combo:
(1)	"uart initialize" [UART]
(2)	"send uart bytes" [UART]
```
this PR fixes #116
> wifi-subsys: async uart implementation

- dist/tools/codespell/check.sh
If we run the static-test codespell be ignored the directory wifi-subsys/build and that fixes Issue #120 Codespell,
look at  dist/tools/codespell/check.sh was added "CODESPELL_OPT+=" --skip=RIOT,dist,./wifi-subsys/build,.git,css,html,js,m4a.doxyfile" "
fixes  #120
> Codespell ignores directory wifi-subsys/build

- wifi-subsys/.gitignore
- wifi-subsys/components/network/src/wifi.c
- wifi-subsys/components/network/src/wifi.h
- wifi-subsys/components/network/test/test_wifi.c
- wifi-subsys/components/tools/idf_component.yml
- wifi-subsys/components/uart/CMakeLists.txt
- wifi-subsys/components/uart/src/subsys_uart.c
- wifi-subsys/components/uart/src/subsys_uart.h
- wifi-subsys/components/uart/test/uart_test.c
- wifi-subsys/main/CMakeLists.txt
Was added the modification of the module wifi for be controlled since uart.
cd test && idf.py build -D "TEST_COMPONENTS=network" flash monitor
```c
Press ENTER to see the list of tests.
I (2803) wifi:ap channel adjust o:6,1 n:4,1
I (2803) wifi:new:<4,0>, old:<6,1>, ap:<4,1>, sta:<4,0>, prof:6
I (3633) wifi:state: init -> auth (b0)
I (3643) wifi:state: auth -> assoc (0)
I (3643) wifi:state: assoc -> run (10)
I (3673) wifi:connected with Chicho, aid = 26, channel 4, BW20, bssid = 60:12:3c:21:03:88
I (3673) wifi:security: WPA2-PSK, phy: bgn, rssi: -64
I (3683) wifi:pm start, type: 1
I (3723) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (6683) esp_netif_handlers: sta ip: 172.16.0.159, mask: 255.255.255.0, gw: 172.16.0.1
I (6683) Wifi Module: got ip:172.16.0.159
Here's the test …
```
> AT and NVS integration 

- wifi-subsys/components/tools/src/serialization.c
- wifi-subsys/components/tools/src/serialization.h
- wifi-subsys/components/tools/test/test_cbor.c
This Pull request referred to control to encode and decode arrays of bytes and data type uint8_t. In these changes could see that decode implement a void pointer, that could be help to manipulate other data types and check every one if is that type. So, this can be util to avoid build some functions to encode and decode... The main proposal is to control it with only a function encode and one function decode... Well, there is some close to upgrade for another cases.
- Upload the program to your develop board esp32-wroom
```sh
idf.py build -D "TEST_COMPONENTS=tools" flash monitor
```
- Then, enter to monitor (Terminal or Serial Communication) and press enter to view all the available tests. 
```sh
Here's the test menu, pick your combo:
(1)	"Encode a int value = 34 of an key_element[0]" …
```
> wifi-subsys: Integration of uint8_t array to Cbor Serialization

- wifi-subsys/components/network/src/protocol_sntp.c
- wifi-subsys/components/network/src/protocol_sntp.h
- wifi-subsys/components/network/test/test_sntp.c
Integrations of sntp protocol to get  the current date, time from an zone in specific. 
this implement two functions, init_sntp to connect with an sntp server anf get_time, that works setting the time of the system
Fixes #134
> wifi-subsys: Adding sntp support to sync time

- wifi-subsys/components/network/src/icmp_ping.c
- wifi-subsys/components/network/src/icmp_ping.h
- wifi-subsys/components/network/test/test_icmp.c
- wifi-subsys/components/network/test/test_wifi.c
- wifi-subsys/main/CMakeLists.txt
- wifi-subsys/main/default_params.h
this pr contains an implementation of ipmc to check the status of the connection, by default the google server was added to check if the esp32 is connected.
cd test && idf.py build -D "TEST_COMPONENTS=network" flash monitor
```c
Press ENTER to see the list of tests.
Here's the test menu, pick your combo:
(1)	"Wi-Fi initialize" [network]
(2)	"setting ping session" [network]
(3)	"send manual ping" [network]
(4)	"get current status" [network]
```
This PR fixes #135
> wifi-subsys: icmp implementation

- wifi-subsys/components/network/src/wifi.c
- wifi-subsys/components/network/src/wifi.h
- wifi-subsys/components/network/test/test_wifi.c
initially this PR was created to return a value when the sta is successfully connected.
The previous implementation was not intended to do this, so the structure had to be modified a bit to make it work correctly.
doing the structure modification I could find several bugs:
1) once connected to a sta and we wanted to connect to another at runtime, the process executed well but the connection was not executed
2) memory overflow when starting wifi_init
3) when stopping the Wi-Fi, the events were not closed when starting the Wi-Fi again, they were initialized again and caused an overflow
4) restart function did not work correctly.
cd test && idf.py build -D "TEST_COMPONENTS=network" flash monitor
```c
Here's the test menu, pick your combo:
(1)	"set default credentials" [network]
(2)	"Wi-Fi …
```
> wifi-subsys: add litle improvements to the wifi module

- wifi-subsys/components/storage/src/storage.c
- wifi-subsys/components/storage/src/storage.h
- wifi-subsys/components/storage/test/test_nvs.c
Add support for storing or reading `uint32_t` type in the Non-Volatile storage 
Run the related tests running the following in the test folder:
```sh
idf.py build -D "TEST_COMPONENTS=storage" flash monitor
```
Select option: _Save a uint32_t in the NVS_ (for storing) 
Select option: Get a previously saved uint32_t from the nvs_ (for reading)
None
> wifi-subsys: add support for storing uin32 integers in the NVS

- wifi-subsys/components/protocols/src/icmp_ping.c
- wifi-subsys/components/protocols/test/test_icmp.c
is necessary do a revert because i din't the squash
Reverts Mesh4all/m4a-firmware#150
> Revert "wifi-subsys: added event group in icmp"

- wifi-subsys/components/protocols/src/icmp_ping.c
- wifi-subsys/components/protocols/test/test_icmp.c
- wifi-subsys/main/main.c
An event group was added to know the exact moment when the icmp finishes making the ping requests.
This was added because after the ping interval was added dynamically, the function responded before icmp finished making the requests, this caused us not to have the current data.
Run the related tests running the following in the test folder:
the PR is related with PR #150 merge by error.
> wifi-subsys: fixed little bug in imcp component

- wifi-subsys/components/network/src/wifi.c
- wifi-subsys/components/network/test/test_wifi.c
- wifi-subsys/test/main/main.c
When i was doing the uart modification i can saw some mistakes in the correct working of wifi module. After to executed the functions: `wifi_restore_default`,`change_wifi_mode`,`change_wifi_sta_pass`,`change_wifi_ap_ssid`.
the WiFi did not retry the reconnection this was fixed in this PR. also i added more unit test and executed a better test.
Run the related tests running the following in the test folder:
> wifi-subsys: fixed little bugs in wifi module

- firmware/libs/at_commands_uart/at_uart.c
- firmware/libs/at_commands_uart/include/at_uart.h
- wifi-subsys/components/uart/src/subsys_uart.c
- wifi-subsys/components/uart/src/subsys_uart.h
The command  "at at"  allows to know if ESP32 after send "atho" 
look at firmware/libs/at_commands_uart/at_uart.c and firmware/libs/at_commands_uart/include/at_uart.h
* Try "at at" command to receive an answer from ESP32 in AT mode.
look at wifi-subsys/components/uart/src/subsys_uart.c
* The answer is \r\nok\r\n if connection is ok
none
> connection_ESP32_at_commands

- firmware/Kconfig
- firmware/peripherals/Kconfig
- firmware/peripherals/ds18_sensor/Kconfig
- firmware/peripherals/moisture_sensor/Kconfig
- firmware/sys/Kconfig
Adds a basic Kconfig function to set some parameters before the build stage
Type:
`make menuconfig`
Should appear the **Kconfig** menu
None
> firmware: add basic Kconfig feature

- firmware/sys/network/Kconfig
- firmware/sys/network/Makefile.dep
- firmware/sys/network/include/uniqueid.h
- firmware/sys/network/uniqueid.c
This function get ipv6 address with the following modes: static (default), random, manual
and with the menuconfig you can change : 
1) The header address (default is 2001:db8)
2) The mode: static, random, manual (by default it's value is set to 1111:2222)
if you choose manual mode you can change the address in menuconfig
look at firmware/sys/network 
test in main with the following commmand:
```
ipv6_addr_t ipv6 = {
.u8 = {0},
};
subnet_to_ipv6(&ipv6);
ipv6_addr_print(&ipv6);
```
Note: Make a change in menuconfig to test modes and change header if you need it
Fixes #174
> Sys: get ipv6 address

- wifi-subsys/components/protocols/src/protocol_sntp.c
Solution to implement an semaphore or mutex control to sntp task, This will bring a better control and prevision to one or more threads are handling or manipulating the same variable or component... 
Test with idf
```
```
> Wifi-subsys: Instance Mutex-Semaphore in SNTP

- wifi-subsys/components/network/doc.txt
- wifi-subsys/components/network/src/wifi.c
- wifi-subsys/components/network/src/wifi.h
- wifi-subsys/components/network/test/test_wifi.c
This Pr brings a little changes and updates in wifi.c, here is resolved all build warnings manifested with some no-casted values called for some nvs functions... Changes the use of int8_t to maintain the standard datatype uint8_t, with this also control the Bit state of event groups, so this will allow that the function wifi_bit_event() could be called from another protocols and networks elements to check if the wifi, is connected or not. Another features to brings this PR, its a better structured documentation of wifi-routines inside the wifi-subsystem element.
```sh
idf.py -D "TEST_COMPONENTS=network" flash monitor
```
Fixes #196
> Wifi updates

- .github/labeler.yml
The **labeler check** should put `Area: doc` and `Area: ci` for  new PRs with changes in `md` files, in  the `.github` folder
- *labeler* shoild works as expected opening a new PR with changes in some of the `*.md` files in the `.github` folder
- or see the **labeler.yml** in `.github/`
None
> ci: update labeler runner

- dist/tools/codespell/check.sh
- dist/tools/codespell/dictionary_m4a.txt
This PR implements a solution to codespell not found misspelling errors, resolves some wrong pointed paths and add an dictionary.txt to run static-test locally. 
There are two ways to test the static test
- First (Running by static test)
```sh
make static-test
```
- Second running in dist/tools/codespell
```c
cd dist/tools/codespell
./check.sh
```
Fix #211
> CI : Fixing Codespell undetected misspelling words during static-test

- firmware/Kconfig
- firmware/network/Kconfig
- firmware/network/udp_client/Kconfig
- firmware/network/udp_server/Kconfig
- firmware/sys/Kconfig
- firmware/sys/at_client/Kconfig
- firmware/sys/serialization/Kconfig
- firmware/sys/storage/Kconfig
- firmware/sys/uniqueid/Kconfig
Makes Kconfig files for Firmware module
- Makes the PHY setting to tx_power and radio channel
Look at  firmware
use command 
``` make menuconfig```
In the following modules the Kconfig files need to be completed:
- Network folder:
* udp_server
* udp_client
- Sys folder:
* at_client
* serialization
*  storage
Fixes #222
> Firmware: makes Kconfig

- wifi-subsys/components/protocols/src/httpsclient.h
- wifi-subsys/components/protocols/src/icmp_ping.c
- wifi-subsys/components/protocols/src/icmp_ping.h
- wifi-subsys/components/protocols/test/test_icmp.c
Implementation of some casting to fix some warning when it's build the protocols software, it's about all sectors of icmp, where was passing by nvs a value `uint8_t` to `uint32_t` pointer-variable, another warning was about `manual_ping` callback param, This function has the proposite is pass a function as parameter, so the `callback_t`  solve this pointer, it's not necessary make a pointer param to get a function... These changes also resolves the previously conflict where a little part of https was erased, 
move to wifi-subsys/test directory and then run:
```sh
```
Fixes #195
> Wifi-subsys: Delete build warnings from icmp and recover https erased element

- firmware/main.c
- firmware/network/radio/Kconfig
- firmware/network/radio/Makefile.dep
- firmware/network/radio/include/radio.h
- firmware/network/radio/include/radio_params.h
- firmware/network/radio/radio.c
Radio module funtions are dependent of get_ieee802154_iface(), these affect to multi-operatibility with various interfaces inside an net device. To resolve this each function could refers to an index of an iface.
current operatibility it's represented:
if it's used get_ieee802154_iface to return a group of ifaces, every iface will be affected by the selected operation. e.g: an device has a driver at86rf233 and a driver at86rf215, if `get_ieee802154_iface()` returns both id ifaces, these same interfaces will be modiffied.
The propose solution it's bring to each option a parameter to refers index of an interface:
An index interface offers a flexibility to setup an interface one by one.
This PR add some radio_params to get TX_POWER of an determinate module... This last feature has to offer a …
> firmware: Radio modification to manage various same type ifaces

- Makefile
- boards/doc.txt
- boards/m4a-24g/Makefile.include
- boards/m4a-mb/Makefile.include
This Pr includes a makefile to be easier the build and dfu flashing an file. Integrate an own bootloader to Mesh4all that provides an Vendor_id and Product_id dedicated to Mesh4all Boards and bootloaders, compilers, itś applied an make variable to define the boot_update mode, the user dotń need to write it, it's conventional gives support to m4a-24g bootloader support features. in the makefile of firmware there are some parameters to define the dfu elements required, as vendor_id as the slot where will be uploaded the firmware. 
only has to connect in EDBG USB and run:
```sh
make install-boot BOARD=m4a-24g
```
- updating your firmware
```sh
make update
```
You should could be run the `make update` how many times that you need to upload the firmware
> Makefile: New Integration to manage bootloader Commands

- boards/m4a-24g/include/eui_provider_params.h
- dist/tools/chamoc/doc.txt
- dist/tools/chamoc/include/chamoc_msg.h
- dist/tools/chamoc/include/client.h
- dist/tools/chamoc/include/nib.h
- dist/tools/doc.txt
- dist/tools/uncrustify/whitelist.txt
- doc/doxygen/m4a.doxyfile
- firmware/network/border_router/doc.txt
- firmware/network/border_router/include/border_router.h
- firmware/network/chamos/doc.txt
- firmware/network/chamos/include/chamos.h
- firmware/network/radio/include/radio_params.h
- firmware/network/rpl_protocol/include/rpl_protocol.h
- firmware/sys/serialization/include/serialization.h
- wifi-subsys/components/protocols/src/httpsclient.h
- wifi-subsys/components/protocols/src/protocol_sntp.h
- wifi-subsys/components/uart/src/at_handler.h
- wifi-subsys/components/uart/src/subsys_uart.h
This PR is solving all warnings presented by the generated doc, this will make changes in firmware modules and the wifi-subsystem elements, has solution to specify the path to the chamoc client files and generate its documentation, specify to ignore all CMakeList.txt files in subsystem to don't received warnings from them. solved some @params interpretation bad written.
Generate the documentation file
```sh
make docs
```
Expected Output:
```sh
make[1]: Entering directory '/home/cyberwolf-75/Documents/m4a-firmware/doc/doxygen'
( cat m4a.doxyfile ; echo "GENERATE_HTML = yes" ) | doxygen -
/home/cyberwolf-75/Documents/m4a-firmware/dist/tools/uncrustify/whitelist.txt:4: warning: Reached end of file while still inside a (nested) comment. Nesting level 3 (probable line reference: 3, 2, 1) …
```
> docs: solved some warnings in the RC-22.06

- firmware/network/border_router/Makefile.dep
- firmware/network/border_router/border_router.c
- firmware/network/border_router/include/border_router.h
- firmware/network/net_tools/include/net_tools.h
- firmware/network/net_tools/net_tools.c
In the `border_router.c`, there is an function called `border_router_add_ipv6()`, will be changed to `border_router_setup()` and the internal effects of set_ipv6 address will be integrated in generic functions in net_tools that could be used in anothers modules, this will resolve when will be necessary take some configuration about the ipv6 address. The new functions `set_ipv6_global()` and `set_ipv6_multicast` are protected if the input parameter isn't the required format of address.
> firmware: Network module net_tools and border_router modifications

- wifi-subsys/components/uart/CMakeLists.txt
- wifi-subsys/components/uart/src/subsys_uart.c
the cjson module was added to encode as json the messages that arrive from uart and send them to the server
> wifi-subsys: added cJSON and changed cbor to json in the https-request

- firmware/network/border_router/Makefile.dep
- firmware/network/border_router/border_router.c
- firmware/network/border_router/include/border_router.h
- firmware/network/net_tools/include/net_tools.h
- firmware/network/net_tools/net_tools.c
- tests/border_router/main.c
These are some modifications to give support with the net_tools changes to the border_router test, in this moment the test is printing the next information:
```
2022-06-10 07:27:28,311 # main(): This is RIOT! (Version: 2021.10-devel-4249-g5f574-HEAD)
2022-06-10 07:27:28,312 # .0x114f
2022-06-10 07:27:28,314 # *** RIOT kernel panic:
2022-06-10 07:27:28,315 # FAILED ASSERTION.
2022-06-10 07:27:28,316 # 
2022-06-10 07:27:28,316 # *** halted.
2022-06-10 07:27:28,317 # 
2022-06-10 07:27:28,317 # 
2022-06-10 07:27:28,319 # Context before hardfault:
2022-06-10 07:27:28,321 #    r0: 0x0000000a
2022-06-10 07:27:28,322 #    r1: 0x00000000
2022-06-10 07:27:28,324 #    r2: 0xc0000000
2022-06-10 07:27:28,325 #    r3: 0x00000000
2022-06-10 07:27:28,327 #   r12: 0x00000028
2022-06-10 07:27:28,329 # …
```
> test/border_router: fixed with the new modifications

- boards/m4a-24g/Kconfig.periph
- boards/m4a-24g/include/periph_conf.h
- firmware/peripherals/Kconfig
- firmware/peripherals/ds18_sensor/Kconfig
This new integration allows configure the VREF via Kconfig. I add the kconfig manipulation to only select an option of `ADC_REF`, so the only way to change by the moment it's using kconfig, when kconfig it's not apply to the application, example or firmware, the system will get the DEFAULT_VALUE of aref --> `ADC_REF_DEFAULT` = `ADC_REFCTRL_REFSEL_INT1V`
> boards/m4a-24g: Adc VREF periph control by KCONFIG

- firmware/network/udp_client/include/udp_client.h
- firmware/network/udp_client/udp_client.c
- tests/udp_client/main.c
- tests/udp_server/main.c
To fix some errors presented in the test of `udp_client` and `udp_server`. It was fixed the specified parameters in udp_client.h, changing the estimation of port from `int` to `uint16_t`, and this parameter should be constant, because the port never be affected or changed by the function. also the max number of internet ports are 65535, this is the maximun reach value in 
`uint16_t`
> network/udp_client: Update udp client to pass the tests

- firmware/sys/uniqueid/Kconfig
- firmware/sys/uniqueid/Makefile.dep
- firmware/sys/uniqueid/doc.txt
- firmware/sys/uniqueid/uniqueid.c
- tests/uniqueid/Kconfig
- tests/uniqueid/main.c
Fixed a random option in module uniqueid  using a seed cryptographically secure with NETOPT_RANDOM and added a function to uniqueid test.
look at ```tests/uniqueid ```
use the command ``` make menuconfig```, click in uniqueid/subnet option and choose ``` random ``` and save.
In to the console write ``` make flash test term```
Fixes #280, see also #279
> Sys: fixed random option uniqueid

- firmware/doc.txt
- firmware/network/radio/doc.txt
- firmware/sys/at_client/doc.txt
Fixes firmware doc
Look at ``` firmware/network/radio/doc.txt ```
Write in to the shell ```make docs ```
> Doc: fixes doc firmware

- firmware/sys/at_client/Kconfig
- firmware/sys/at_client/at_client.c
- firmware/sys/at_client/include/at_client.h
- tests/at_client_test/Kconfig
Made kconfig to at client module with the kconfig sets the configuration to baudrate default, shell and uart buff size
Run in terminal ```make menuconfig```, look for the option at client and choose baudrate default, shell and uart buff size
> Network: Made kconfig to at_client

- firmware/sys/storage/Makefile.dep
- firmware/sys/storage/include/storage.h
- firmware/sys/storage/storage.c
- tests/storage/main.c
This PR implement a solution to compress the data blocks in a flashpage of mtd.  The actually module presents a change in `mtd_save`, and `mtd_load`, here will be the save a defined struct or variable by the storage block
*note*: the current mode saves the data in the respective order, this means that when it's necessary read the data, you will received it in the same order that was saved.
- Support to compressed mode --> (This will allow use correctly the memory size distribution)
- Support to load storage --> (Allow load all data compressed in the storage).
- Better definition of the `MAX_SIZE_STORAGE`,  `MAX_NUMOF_FLASHPAGES`, `LAST_AVAILABLE_PAGE`
- The initialization of device was fixed making the param `_pages persector` take the value of `FLASH_PAGES_PER_ROW`  
go to test
```
make …
```
> Storage: compress model to flashpages blocks

- .github/labeler.yml
The labeler runner assigns labels according to the `labeler.yml` file when a new pr is opened or updated,  in a past PRs a new board was added, this pr takes into account those changes adding the labels; `Platform: meshme` and `Platform: vs203` for a future PR.
The labeler runner assigns labels according to the `labeler.yml` file, so new labels should appear in future PRs
or look the new changes in `labeler.yml` under `.gtihub` path
None
> ci: update labeler runner with new board's label

- firmware/network/chamos/Kconfig
- firmware/network/chamos/chamos.c
- firmware/network/radio/radio.c
Made kconfig to chamos module with the kconfig sets the configuration to IPV6 address, the size of message and the buffer
Run in terminal make menuconfig, look for the option chamos and choose of the IPV6 address, the size of message and the buffer
> Network: Made kconfig to chamos

- examples/moisture_sensor_hw390/Kconfig
- examples/moisture_sensor_hw390/main.c
- firmware/peripherals/Kconfig
- firmware/peripherals/ds18_sensor/Kconfig
- firmware/peripherals/moisture_sensor/Kconfig
- firmware/peripherals/moisture_sensor/moisture_sensor.c
- tests/ds18/Kconfig
- tests/ds18/main.c
Made kconfig to ds18 and moisture sensor module with the kconfig sets the configuration to pin for ds18 module and values default of moisture sensor.
Run in terminal make menuconfig, look for the option ds18 or moisture sensor.
> Network: Made kconfig to ds18 and moisture sensor

- boards/vs203/board.c
Fix compilation error; `BTN1 not defined`
Build firmware w/; `make BOARD=vs203`
Build process should raise another error in the compilation process related to `storage module`: #314
> boards: fix error, BTN1 not defined

- Makefile
- firmware/Makefile
- tests/riotboot/Makefile
- tests/riotboot/Makefile.ci
- tests/riotboot/README.md
- tests/riotboot/main.c
- tests/riotboot/tests/01-run.py
This PR lets, to use riotboot serial in the new boards meshme and vs203, while both boards doesn´t have an `periph/usbdev`, the mode DFU is unsupported. This PR adds an new test model to run riotboot (test/meshboot). Here is a mode to test the bootloader works correctly with the new boards
Firmware testing procedure: (ATomatization of Bootloader with the firmware)
Run the make `install boot`
```
make install-boot BOARD=meshme
```
next step is update your firmware with any change:
```
make update BOARD=meshme
```
Running the test meshboot:
```
BOARD=meshme make -C flash test
```
*note*: this test run in m4a-24g by default, you need to asign the new boards as value of enviroment variable `BOARD` 
Fixes #296 .
> Meshboot: Supporting to install boot in meshme and vs203 boards

- boards/meshme/board.c
- boards/meshme/include/board.h
- boards/meshme/include/gpio_params.h
- boards/meshme/include/periph_conf.h
- tests/periph_adc/Makefile
- tests/periph_adc/app.config.test
- tests/periph_adc/doc.txt
- tests/periph_adc/main.c
- tests/periph_adc/tests/01-run.py
This PR contains two **related** commits:
-  Add support for ADC peripheral on two lines of the `meshme` platform
-  `tests/periph_adc`
Run the `periph_adc` test with:
```sh
make BOARD=meshme flash test
```
None
> boards/meshme: Add ADC support and tests

- .drone.yml
Recently was added cc2538 in two flavors to the `drone` runners, this PR add  these two boards to the drone's test
Nothing special, when a new PR is open, updated or merged look at the runners list and search the luke/skywalker's details, the "matrix build" should show you 4 builds/test:
- m4a-24g
- m4a-mb
- meshme
- vs203
None
> ci: add new platforms to  drone runners

- firmware/sys/storage/include/storage.h
- firmware/sys/storage/storage.c
Contribution to provide support of storage module to new boards: was fixed reference to generic literals. FLASHPAGE_SIZE as `MAXIMUN_SIZE_STORAGE` and `MAX_NUMOF_FLASHPAGEs` as `FLASHPAGE_NUMOF`
Testing with each board in test/storage
```
make -C tests/storage flash term
```
> firmware/storage: Fixed bug in Boards meshme and vs203

- tests/ds18/main.c
- tests/radio/main.c
- tests/serialization/main.c
This PR is to fix the wrong names writen in some tests. was renamed to correct name for each test.
test only building each test:
```
make -C tests/serialization
```
```
make -C tests/radio
```
Note: Please before to run the test  ds18, connect your peripheral in the pin `CONFIG_PIN_TEMP_SENSOR`. (by default is the pin 5 of m4a-24g)
```
make -C tests/ds18
```
```
2022-07-19 21:42:01,471 # START
2022-07-19 21:42:01,476 # main(): This is RIOT! (Version: 2022.07-devel-934-g6b7d8-HEAD)
2022-07-19 21:42:01,477 # ..
2022-07-19 21:42:01,478 # OK (2 tests)
2022-07-19 21:42:08,182 # Exiting Pyterm
```
```
2022-07-19 21:45:17,493 # START
2022-07-19 21:45:17,498 # main(): This is RIOT! (Version: 2022.07-devel-934-g6b7d8-HEAD)
2022-07-19 21:45:17,500 # ..TX-Power: 0dBm 
2022-07-19 21:45:17,502 # …
```
> tests: renamed tests with correctly test name

- firmware/sys/uniqueid/Kconfig
- firmware/sys/uniqueid/Makefile.dep
- firmware/sys/uniqueid/uniqueid.c
- tests/uniqueid/main.c
The uniqueid was presenting a compilation errors in others boards. so to fix this was added an dependency conditionals that check and verify if the device has or not the required hardware. Another important feature added is the condition that is not has the required hardware only could be work with two mode (`STATIC` and `MANUAL`). 
```
make BOARD=cc1352p-launchpad menuconfig
```
Fixes #319
> sys/uniqueid: Fixed compilation dependencies of HWRNG and radio hardware

- firmware/sys/storage/include/storage.h
- firmware/sys/storage/storage.c
- tests/storage/main.c
This new PR implements a new model to run the storage module, I recommend let this module in constantly review, because is throwing a cppcheck static test alert, that was suppressed. Well the new model to use `mtd_save_compress` and `mtd_load()` is working, but the old functions of storage, are freezing the terminal when it's running the test. So this new PR are providing support to cc2538 boards (`meshme`, `vs203`), the m4a-24g and the m4a-mb board.
Start running the storage test:
```
make -C test/storage BOARD=meshme flash term
```
In meshme board
```
..
Saving data:
numpages : 1
.
Loading data:
varui8_attr1 [1]: 2
varui8_attr1 [2]: 5
varui8_attr1 [3]: 6
varui8_attr1 [4]: 7
varui8_attr1 [5]: 8
varui8_attr1 [6]: 9
varui32_attr2 [1]: 1555
varui32_attr2 [2]: 2556
varui32_attr2 [3]: 477 …
```
> test/storage: Support to cc2538 with `mtd_save_compress` and `mtd_load`

- boards/meshme/include/periph_conf.h
- tests/doc.txt
- tests/driver_bme280/Makefile
- tests/driver_bme280/app.config.test
- tests/driver_bme280/doc.txt
- tests/driver_bme280/main.c
- tests/driver_bme280/tests/01-run.py
- tests/periph_adc/doc.txt
- tests/periph_i2c/Makefile
- tests/periph_i2c/app.config.test
- tests/periph_i2c/doc.txt
- tests/periph_i2c/main.c
- tests/periph_i2c/tests/01-run.py
This PR add initial support for **I2C** and **SPI** peripherals for **Meshme** board
Build and flashing procedures for **Meshme** board should works as expected with the new changes but also with two new test:
- `tests/periph_i2c`   
- `tests/driver_bme280`
This pull request could open a new issue: 
- A low level test for **SPI** peripherals should be added
Not now but it should be added in the short term
> boards/meshme: initial implementation of I2C and SPI peripherals

- firmware/network/radio/radio.c
This contribution adds support to unregistered network devices, example if the netdev interface doesn't exist, All the operations of the module, should be stopped.
The test with `cc1312-launchpad` board.
step to provide the uniflash programmer (also could be used openocd as programmer)
```
export PROGRAMMER=uniflash
```
then, run the test radio.
```
make -C tests/radio flash term BOARD=cc1312-launchpad
```
Well, if the device doesn't have a radio interface, the all ran tests should been failed.
```
2022-07-25 17:36:57,965 # radio_tests.test_get_netopt_channel (/home/eduardo-az/github-forks/m4a-firmware/tests/radio/main.c 40) exp 0 was -1
2022-07-25 17:36:57,979 # .Error: Radio interface doesn't exist, File:/home/eduardo-az/github-forks/m4a-firmware/firmware/network/radio/radio.c line:69 …
```
> firmware/radio: Compillation Fixed to unregister netdev devices

- Makefile
- examples/Makefile.common
- examples/blinking/Makefile
- examples/mesh4all_rpl_dag/Makefile
- examples/mesh4all_rpl_dodag/Makefile
- examples/system_example/Makefile
- firmware/Makefile
- makefiles/tools/bootloader.mk
- makefiles/tools/firmupdater.mk
- tests/Makefile.tests_common
- tests/riotboot_dfu/Makefile
- tests/riotboot_dfu/README.md
- tests/riotboot_dfu/main.c
- tests/riotboot_dfu/tests/01-run.py
this propose the riotboot works in each app directory, (examples, tests and firmware). The new feature is that any app actually could be updated via riotboot or `dfu` . Something else that was added is the resetting of device after to build and flash (via bootloader) the firmware or source code.
FIrst you need to add the bootloader in your m4a-24g board
```
make install-boot
```
This will build and flash in the board a bootloader to manage two flash slots. (Always manipulate the slot_0)
Then, you could try upload and sample or test application using the bootloader updater.
```
make -C examples/blinking update
```
> riotboot: Riotboot features

- firmware/network/rpl_protocol/Makefile
A few `C` flags allow alternative parents and add space for increasing the number of nodes network nodes.
Number of alternative parents, is set to 2, so the minimum setup needs at least  3 nodes:
- 2 as DODAG, build and flash `mesh4all_rpl_dodag`
- 1 as DAG, build and flash `mesh4all_rpl_dag`
Turn on all nodes and make sure the two **DODAG** nodes are using different IPV6 addresses.
Open a terminal on the **DAG** node and verify that it can use alternative parents.
Using `zep` create a network at least of 50 nodes acting as DAG and only one as dodag, turn all nodes on.
The DODAG node should show you 50 entries, it correspond to 50 DAG nodes in the network
None
> firmware: confs. for a better performance of RPL routing protocol.

- dist/tools/chamoc/doc.txt
- firmware/Kconfig
- firmware/Kconfig.debug
- firmware/network/border_router/border_router.c
- firmware/network/chamos/chamos.c
- firmware/network/net_tools/net_tools.c
- firmware/network/radio/radio.c
- firmware/network/rpl_protocol/rpl_protocol.c
- firmware/network/udp_client/udp_client.c
- firmware/network/udp_server/udp_server.c
- firmware/peripherals/ds18_sensor/ds18_sensor.c
- firmware/peripherals/moisture_sensor/moisture_sensor.c
- firmware/sys/at_client/at_client.c
- firmware/sys/serialization/serialization.c
- firmware/sys/storage/storage.c
- firmware/sys/uniqueid/uniqueid.c
This PR adds debug mode in each module, This will implement the capacity to test each module and print all data processed sent or saved. Was added debug mode in kconfig. you should load in any module used by a test or an example application. 
Load the menuconfig
```
make menuconfig flash term
```
Then enter in debug mode menu, you should options, those options are the sub-categories from firmware modules. seek and select the wished module to run the debug mode inside it.
> firmware: Adding DEBUG mode to each module

- examples/border_router/Makefile
- examples/border_router/Makefile.native.conf
- firmware/network/chamos/chamos.c
- firmware/network/radio/radio.c
These features allow use the socket_zep and zep_dispatcher tool, to simulate an radio network. You could use various border_router in a radio simulated network modifying the `TAP`and `PORT`parameters. Remember that you also need to refer the type board as native to work with socket_zep. (by default is set m4a-24g board). 
*Note*: Don't reboot the border routers during their use, you will get the settings of the last built border_Router tap example.
Open the foren 6, and select play. [more about foren6](https://cetic.github.io/foren6/), only available through a [fork](https://github.com/benpicco/foren6)
start running zep_dispatch in another terminal
```sh
cd RIOT/dist/tools/zep_dispatch
make run
```
Build, flash and open terminal of the example
```
make -C examples/border_router/ …
```
> examples: border router added support to foren6

- firmware/network/rpl_protocol/rpl_protocol.c
- firmware/sys/Makefile
- firmware/sys/uniqueid/Kconfig
- firmware/sys/uniqueid/include/uniqueid.h
- firmware/sys/uniqueid/uniqueid.c
- tests/uniqueid/main.c
Uniqueid presents some changes about its static model. Kconfig parameters dependency was removed, uniqueid functions will be to use random number generation and cpuid information to get an ipv6 address. Tests of unique id was modified to get in real time these random and static ipv6 address. The manual mode was removed, this is the same to set an ipv6 address using `net_tools`.  Also the uniqueid model presents the new random generation seed to provide an unique id value during a real time operation, this will allow use this module via `shell_commands_extends`
Use the uniqueid test
```
make -C tests/uniqueid flash term
```
> sys/uniqueid: Uniqueid model RTOS

- firmware/network/net_tools/include/net_tools.h
- firmware/network/net_tools/net_tools.c
- firmware/network/rpl_protocol/Makefile.dep
- firmware/network/rpl_protocol/rpl_protocol.c
- firmware/sys/uniqueid/Makefile.dep
- firmware/sys/uniqueid/include/uniqueid.h
- firmware/sys/uniqueid/uniqueid.c
- tests/net_rpl/Makefile
- tests/net_rpl/main.c
- tests/system_uniqueid/Makefile
- tests/system_uniqueid/main.c
- tests/system_uniqueid/random_gen.c
The uniqueid module was modified to only generate a random or statically seed (Whatever mode that is required). You could get a value from the cpuid, the seed requires to know the length of the passed storage value (`len`), if the length is biggert than CPUID_LEN in bytes,  The rest of the remaining bytes will be filled with random values.
To net_tools set_ipv6_by_uid only will be used is module uniqueid is added. you always need to add the ipv6_header that is pre-defined by the prefix length. e.g  prefix will be used "/56" the address "[2001:db8:0021:15]()xx:xxxx:xxxxx:xxxxx:xxxx", each "x" refers to a value that can be altered by the `uid_seed`. 
```
make -C tests/system_uniqueid flash term
```
> firmware/sys/uniqueid: get_uid_seed and net_tools set_ipv6_by_uid

- firmware/sys/shell_extended/se_uniqueid.c
`shell extended` for `unique id` module was added in a previous PR as a mockup, this PR add functionality for both modes available on `uniqueid` module:
- static:  it's based on the CPU ID 
- random: Use any of  **hwrng**s available in some MCUs, or random bytes from radio interface when available
Build and flash `examples/shell_extended`, both commands previously described are available as `uid static` or `uid random`
> firmware/sys/shell_extended: shell extended functionality  for uniqueid

- firmware/sys/storage/Makefile.dep
- firmware/sys/storage/include/storage.h
- firmware/sys/storage/storage.c
- tests/system_storage/Kconfig
- tests/system_storage/Makefile
- tests/system_storage/main.c
Was Added support to provide an specified data types registers, can be processed `uint8_t`, `uint16_t`, and `uint32_t` for all unsigned data types, for signed datatypes `ìnt8_t`, `int16_t` and `ìnt32_t`, also could be processed `strings` data types, only specifying its length.
run the storage test. `tests/system_storage/`
```
make -C tests/system_storage flash term
```
> firmware/sys/storage: Added supports to save specified data types

- firmware/sys/storage/Makefile
- firmware/sys/storage/include/storage.h
- firmware/sys/storage/include/storage_internal.h
- firmware/sys/storage/include/storage_register.h
- firmware/sys/storage/storage.c
- firmware/sys/storage/storage_internal.c
- firmware/sys/storage/storage_register.c
- tests/system_storage/main.c
This Pr includes support to delete a register from mtd, then that register is erased, it's moved all them registers, compressing the data pointed, and the data inside of register. (Delete process creates a copy of the mtd_register indexes and content dynamically). Another new feature is setting a bit read/write protection, for each method used. Also `mtd_dump`in debugger mode adds the address number, the `mtd_available_idx`was changed to receive two parameters `*idx` and `*count`. where the pointer `idx` should returns the last available address, and the `count` pointer receives the number of empty registers. 
use the test of storage module, and using kconfig parameters, set in debug mode. Select Debug for Test application and the module.
```
make -C tests/system_storage/ menuconfig flash …
```
> firmware/sys/storage: Added supports to del registers and rwp bit set

- firmware/network/radio/include/radio.h
- firmware/network/radio/radio.c
- tests/driver_radio/Kconfig
- tests/driver_radio/main.c
Currently the `gets`function from radio module are not returning the tx_power or channel. only are printing in debug mode, within of the function. so, if you want to read the value of `tx_power`or `channel` already it's accessible. 
There is a little delay to set the `tx_power` of radio interface, you can see that in `driver_radio` test. if you remove that delay, you could see the Tx_power in 0. 
Run using the `tests/driver_radio`
```
make -C tests/driver_radio flash term
```
> firmware/network/radio: Radio module fixed `gets` functions

- examples/shell_extended/Kconfig
- examples/shell_extended/Makefile
- firmware/default_params.h
- firmware/sys/Kconfig
- firmware/sys/shell_extended/Makefile.include
- firmware/sys/shell_extended/se_net_tools.c
- firmware/sys/shell_extended/se_storage.c
- firmware/sys/storage/storage_internal.c
- tests/driver_radio/main.c
- tests/net_net_tools/main.c
To use `shell_extended`  storage commands, saves, loads, and deletes, only writing and reading an interface struct defined in #363 (This pr is merged with #363 and #362). implementing radio `gets` and `sets`, these functions allow you save set parameters in the mtd, and after read them, automatically, set that configuration in your own device. 
Another little bugs were fixed from `storage` module, and `shell_extended` module
Run the shell_extended example.
```
make -C examples/shell_extended flash term
```
- firs step command line testing (use `ifconfig` to set radio parameters {tx_power, channel} )
```
ifconfig [id radio interface] set power 4
ifconfig [id radio interface] set channel 20
```
- check your settings
```
> ifconfig
2022-10-13 19:48:21,456 # ifconfig
2022-10-13 19:48:21,463 # …
```
> firmware/sys/shell_extended: Added `stg` commands functions and `se_*` fixes
